/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 10;
  /** RegularExpression Id. */
  int NUM = 11;
  /** RegularExpression Id. */
  int PLUS = 12;
  /** RegularExpression Id. */
  int MULT = 13;
  /** RegularExpression Id. */
  int SPACE = 14;
  /** RegularExpression Id. */
  int FUNCNAME = 15;
  /** RegularExpression Id. */
  int PARAM = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"DEF\"",
    "\"MAIN\"",
    "<NUM>",
    "\"+\"",
    "\"*\"",
    "\" \"",
    "<FUNCNAME>",
    "<PARAM>",
  };

}
