/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACKET = 1;
  /** RegularExpression Id. */
  int RBRACKET = 2;
  /** RegularExpression Id. */
  int LBRACE = 3;
  /** RegularExpression Id. */
  int RBRACE = 4;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int DEF = 6;
  /** RegularExpression Id. */
  int MAIN = 7;
  /** RegularExpression Id. */
  int NUM = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MULT = 10;
  /** RegularExpression Id. */
  int SPACE = 11;
  /** RegularExpression Id. */
  int FUNCNAME = 12;
  /** RegularExpression Id. */
  int PARAM = 13;
  /** RegularExpression Id. */
  int EOL = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"DEF\"",
    "\"MAIN\"",
    "<NUM>",
    "\"+\"",
    "\"*\"",
    "\" \"",
    "<FUNCNAME>",
    "<PARAM>",
    "\"\\n\"",
  };

}
